# Generated by Django 5.2.17 on 2026-08-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='detections/annotated/')),
                ('counts', models.JSONField(default=dict)),
                ('total_vehicles', models.IntegerField(default=0)),
                ('emergency_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detection_events', to='core.intersection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
