# Generated by Django 5.2.17 on 2026-08-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection_id', models.CharField(max_length=200, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('road', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('coord_source', models.CharField(default='curated', max_length=50)),
                ('num_approaches', models.IntegerField(default=4)),
                ('default_green_seconds', models.IntegerField(default=45)),
                ('hist_mean_volume', models.FloatField(blank=True, null=True)),
                ('hist_mean_congestion', models.FloatField(blank=True, null=True)),
                ('hist_severe_rate', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area', 'road'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], default='INFO', max_length=10)),
                ('module', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temp_celsius', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('condition', models.CharField(blank=True, max_length=50, null=True)),
                ('wind_kph', models.FloatField(blank=True, null=True)),
                ('visibility_km', models.FloatField(blank=True, null=True)),
                ('precipitation_mm', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='openmeteo', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Weather records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TrafficData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_date', models.DateField()),
                ('vehicle_count', models.FloatField(blank=True, null=True)),
                ('avg_speed_kph', models.FloatField(blank=True, null=True)),
                ('travel_time_index', models.FloatField(blank=True, null=True)),
                ('congestion_level', models.FloatField(blank=True, null=True)),
                ('capacity_utilization', models.FloatField(blank=True, null=True)),
                ('incident_reports', models.FloatField(blank=True, null=True)),
                ('env_impact', models.FloatField(blank=True, null=True)),
                ('pt_usage', models.FloatField(blank=True, null=True)),
                ('signal_compliance', models.FloatField(blank=True, null=True)),
                ('parking_usage', models.FloatField(blank=True, null=True)),
                ('ped_count', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, max_length=50, null=True)),
                ('roadwork', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(choices=[('dataset', 'Dataset'), ('live', 'Live'), ('camera', 'Camera'), ('manual', 'Manual')], default='dataset', max_length=10)),
                ('is_synthetic', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='core.intersection')),
            ],
            options={
                'verbose_name_plural': 'Traffic data',
                'ordering': ['-recorded_date'],
                'indexes': [models.Index(fields=['intersection', '-recorded_date'], name='core_traffi_interse_045686_idx')],
                'unique_together': {('intersection', 'recorded_date')},
            },
        ),
    ]
