# Generated by Django 5.2.17 on 2026-08-10 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('ambulance', 'Ambulance'), ('fire', 'Fire Engine'), ('police', 'Police'), ('other', 'Other')], max_length=20)),
                ('plate_number', models.CharField(blank=True, default='', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('route_cleared', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('intersection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_vehicles', to='core.intersection')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('red', 'Red'), ('yellow', 'Yellow'), ('green', 'Green')], default='green', max_length=10)),
                ('green_duration_seconds', models.IntegerField(default=45)),
                ('is_emergency_override', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intersection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signal_state', to='core.intersection')),
            ],
            options={
                'verbose_name': 'Signal state',
                'verbose_name_plural': 'Signal states',
            },
        ),
    ]
